Update ch01-02-hello-world.md
Arg -p or --path is required (cairo-lang-runner 1.0.0-alpha.6) : 

cairo-run main.cairo
error: Found argument 'main.cairo' which wasn't expected, or isn't valid in this context

Usage: cairo-run [OPTIONS] --path <PATH>

For more information try '--help'